# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'HFStock' do
 pod 'HFLibs’, :git => 'https://github.com/helfyz/HFLibs.git', :commit => '55fe26a'
 pod 'AFNetworking'
 pod 'YYKit'
 pod 'FMDB'

end

